- name: OpenLDAP folder creation
  file:
    path: "{{ openldap_home }}"
    state: directory

- name: OpenLDAP docker-compose creation
  template:
    src: docker-compose.yaml.j2
    dest: "{{ openldap_home }}/docker-compose.yaml"

- name: OpenLDAP start
  community.docker.docker_compose:
    project_src: "{{ openldap_home }}"

- name: Wait for OpenLDAP to be ready
  wait_for:
    port: 1389

- name: Verify OpenLDAP is running
  command: ldapvi -h ldap://localhost:1389 -D 'cn={{ openldap_admin_username }},{{ openldap_root }}' -b '{{ openldap_root }}'
