- hosts: localhost

  roles:
    - name: openldap
      tag:
        - openldap
        - docker
    - name: traefik
      tag:
        - traefik
        - docker
    - name: whoami
      tag:
        - whoami
        - docker
