- name: Init service
  file:
    path: "{{ traefik_home }}"
    state: directory

- name: Docker-compose file creation
  template:
    src: docker-compose.yaml.j2
    dest: "{{ traefik_home }}/docker-compose.yaml"

- name: Network creation
  community.docker.docker_network:
    name: traefik

- name: Start service
  community.docker.docker_compose:
    project_src: "{{ traefik_home }}"
