- name: Init service
  file:
    path: "{{ traefik_home }}"
    state: directory

- name: Configuration file creation
  template:
    src: traefik-config.yaml.j2
    dest: "{{ traefik_home }}/traefik-config.yaml"

- name: Start service
  community.docker.docker_compose:
    project_src: "{{ traefik_home }}"
    detached: yes
