- name: Init service
  ansible.builtin.file:
    path: "{{ nginx_home }}"
    state: directory

- name: Docker-compose file creation
  ansible.builtin.template:
    src: docker-compose.yaml.j2
    dest: "{{ nginx_home }}/docker-compose.yaml"

- name: Start service
  community.docker.docker_compose:
    project_src: "{{ nginx_home }}"
