- hosts: localhost

  vars:
    openldap_server: "ldap://localhost:1389"

  roles:
    - name: openldap
      tag:
        - openldap
        - docker
    - name: traefik
      tag:
        - traefik
        - docker
    - name: whoami
      tag:
        - whoami
        - docker

- hosts: whoami_group
  roles:
    - name: whoami
      tag:
        - whoami
        - docker
      vars:
        domain: "whoami.localhost"

- hosts: apache_group
  roles:
    - name: apache
      tag:
        - apache
        - docker
      vars:
        domain: "my-site.localhost"
        path: "/front"

- hosts: nginx_group
  roles:
    - name: nginx
      tag:
        - nginx
        - docker
      vars:
        domain: "my-site.localhost"
        path: "/api"
