- hosts: localhost

  vars:
    openldap_server: "ldap://localhost:1389"

  roles:
    - name: openldap
      tag:
        - openldap
        - docker
    - name: traefik
      tag:
        - traefik
        - docker
    - name: whoami
      tag:
        - whoami
        - docker
